### ISSUE TITLE
TypeError: Cannot read property 'write' of null when connection is killed in combination with link cache

### ISSUE THREAD

**Issue by geoffreysamper** [mbroadst/amqp10-link-cache#11]
@mbroadst : I was testing some code when my connection get lost what happens with the program. When I'm using the link cache the reconnection mechanisme doesn't work and I get follow error. 
When I remove the the link cache the reconnections  works and everything goes fine
Here is the screencast when the we use the linkcache and the connection get killed 
- [with link cache](https://www.screencast.com/t/8ZVFihHPG7) reconnect is not working
- [without link cache](https://www.screencast.com/t/Cc6Jzpfekj) reconnect is WORKING

I used follow version of amqp10
- master
- lastest release on npm 
- branch fix-sender-flow

they all had the same issue

I made a small node app to simulate the issue [see github repo](https://github.com/geoffreysamper/amqp-issue-multi-client-same-eventhub/)
more instruction are available in the readme

```
error while sending TypeError: Cannot read property 'write' of null
    at Object.frames.writeFrame (c:\github\amqp-issue-multi-client-same-eventhub\node_modules\amqp10\lib\frames.js:56:9)
    at Connection.sendFrame (c:\github\amqp-issue-multi-client-same-eventhub\node_modules\amqp10\lib\connection.js:328:10)
    at SenderLink.Link.attach (c:\github\amqp-issue-multi-client-same-eventhub\node_modules\amqp10\lib\link.js:136:27)
    at SenderLink.attach (c:\github\amqp-issue-multi-client-same-eventhub\node_modules\amqp10\lib\sender_link.js:36:38)
    at Session.createLink (c:\github\amqp-issue-multi-client-same-eventhub\node_modules\amqp10\lib\session.js:226:10)
    at attach (c:\github\amqp-issue-multi-client-same-eventhub\node_modules\amqp10\lib\amqp_client.js:240:32)
    at c:\github\amqp-issue-multi-client-same-eventhub\node_modules\amqp10\lib\amqp_client.js:244:5
    at Promise.module.exports.Promise._execute (c:\github\amqp-issue-multi-client-same-eventhub\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise.module.exports.Promise._resolveFromExecutor (c:\github\amqp-issue-multi-client-same-eventhub\node_modules\bluebird\js\release\promise.js:481:18)
    at new Promise (c:\github\amqp-issue-multi-client-same-eventhub\node_modules\bluebird\js\release\promise.js:77:14)
    at AMQPClient.createSender (c:\github\amqp-issue-multi-client-same-eventhub\node_modules\amqp10\lib\amqp_client.js:233:10)
```

**Comment by geoffreysamper** [comment]
@mbroadst Hi I attempted to do a fix but when I did i fix. After serveral killed connections I received an overcapaticity errror on the handle. Do you have any idea what the best way to fix this issue

**Comment by mbroadst** [comment]
@geoffreysamper I think the better way to handle this case is to dynamically check if the client currently supports reattach and switch on that for whether it should be removed from the cache. This can easily be done by looking at the link's policy and determining if [reattach](https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/policies/policy.js#L178) is not null. I think the harder thing here is going to be to write some unit tests to simulate this case

**Comment by geoffreysamper** [comment]
Ok but during reconnection mode is need to know that it is save that i can return a link. The reason if I don't I will get a leak somewhere. 

DO you mean follow 

```javascript
function createlink(....){
 if (client.policy.sender.reattach != null && !connectionReady){
    Promise.reject('not ready in reconnection');
}
````

or do you mean something like this remember this is psuudo code because I need to this to for the receive client

```javascript
function createlink() {
    var linkHash = hash({
        type: type,
        address: address,
        options: options
    });
  
    if (client.links.hasOwnProperty(linkHash)) {
        var entry = client.links[linkHash];
        if (entry.hasOwnProperty('link') && connectionReady) {
            // NOTE: this returns an existing Promise for the link
            return entry;
        }
        if (entry.hasOwnProperty('link') && !connectionReady && client.policy.Senderlink != null) {
            delete client.links[linkHash];
        } else {

            var linkPromise = method(address, options).links[linkHash].stamp = Date.now();
            return Promise.resolve(client.links[linkHash].link);
        }
    }
  
  	var linkPromise = method(address, options);
  	...

}

```
The problem with the second code is that I will get the previous error but I'm not sure. If this is not right can you write some pseudo code for me so that I can understand it.

**Comment by mbroadst** [comment]
@geoffreysamper Let's say we are caching a `SenderLink`. In the main driver, if reconnect is enabled for the link and a disconnect event occurs, the link will attempt to reconnect. You can keep that link around and continue to `send` on it, and it will buffer it up as a pending send in order to be later delivered when reconnection occurs.  Also during the disconnect/reconnect process, the link will accurately emit `detached`/`attached` signals letting you track their state. 

The link cache currently assumes that whenever a `detached` signal occurs, it should [delete](https://github.com/mbroadst/amqp10-link-cache/blob/master/index.js#L39) the link from the cache  - this is incorrect behavior if the link is in fact configured to automatically reattach. Instead, it should simply leave it in the cache and assume that it will reconnect in the future. The only other alternative is for you to disable reattach/reconnect altogether, an track all of this state yourself.

My suggestion is similar to your pseudo-code above, but that logic would be inside the `once('detached')` code I linked to above. In fact, you could theoretically just put an `if` around that `once` code and bypass registering the event listener all together if the link is configured to automatically reattach.

**Comment by geoffreysamper** [comment]
So if there is a reattach policy then do not delete the link from cache. Is this right




Get Outlook for Android









On Tue, Feb 14, 2017 at 9:28 PM +0100, "Matt Broadstone" <notifications@github.com> wrote:












@geoffreysamper Let's say we are caching a SenderLink. In the main driver, if reconnect is enabled for the link and a disconnect event occurs, the link will attempt to reconnect. You can keep that link around and continue to send on it, and it will buffer it up as a pending send in order to be later delivered when reconnection occurs.  Also during the disconnect/reconnect process, the link will accurately emit detached/attached signals letting you track their state.


The link cache currently assumes that whenever a detached signal occurs, it should delete the link from the cache  - this is incorrect behavior if the link is in fact configured to automatically reattach. Instead, it should simply leave it in the cache and assume that it will reconnect in the future. The only other alternative is for you to disable reattach/reconnect altogether, an track all of this state yourself.

**Comment by mbroadst** [comment]
@geoffreysamper yes that sounds correct to me

**Comment by mbroadst** [comment]
@geoffreysamper hey I cleaned up your patch and merged it in, can you test please?

**Comment by geoffreysamper** [comment]
Hi,

Need to test it from the master branch? Will tomorrow morning utc +1.

**Comment by mbroadst** [comment]
@geoffreysamper yes if possible, I'd like to get a test in before pushing the patch release to npm
